(define (find-shared-items datum)
  (let ((visited (make-eq-hash-table))
        (shared '()))
    (define (walk form)
      (when (or (pair? form) (vector? form) (bytevector? form) (string? form) (box? form))
        (if (hash-table-ref/default visited form #f)
            (unless (memq form shared)
              (set! shared (cons form shared)))
            (begin
              (hash-table-set! visited form #t)
              (cond ((pair? form) (walk (car form)) (walk (cdr form)))
                    ((vector? form) (let ((len (vector-length form)))
                                      (let loop ((i 0))
                                        (when (< i len)
                                          (walk (vector-ref form i))
                                          (loop (+ i 1))))))
                    ((box? form) (walk (unbox form))))))))
    (walk datum)
    shared))
