(include "shared.scm")

(define display
  (case-lambda
   ((obj) (display obj (current-output-port)))
   ((obj port)
    (unless (and (output-port? port) (textual-port? port))
      (error "not a textual output port"))
    (cond ((string? obj)
           (write-string obj port))
          ((symbol? obj)
           (write-string (symbol->string obj) port))
          ((char? obj)
           (write-char obj port))
          ((pair? obj)
           (print-list obj port #t))
          ((vector? obj)
           (print-vector obj port #t))
          ((box? obj)
           (print-box obj port #t))
          (else (write obj port))))))

(define write
  (case-lambda
   ((obj) (write obj (current-output-port)))
   ((obj port)
    (unless (and (output-port? port) (textual-port? port))
      (error "not a textual output port"))
    (cond ((string? obj)
           (write-string (quoted-string obj #\" #f) port))
          ((number? obj)
           (write-string (number->string obj) port))
          ((symbol? obj)
           (write-string (quoted-string (symbol->string obj) #\| #t) port))
          ((boolean? obj)
           (write-string (if obj "#t" "#f") port))
          ((void? obj)
           (write-string "#<void>" port))
          ((char? obj)
           (print-char obj port))
          ((null? obj)
           (write-string "()" port))
          ((pair? obj)
           (print-list obj port #f))
          ((vector? obj)
           (print-vector obj port #f))
          ((bytevector? obj)
           (print-bytevector obj port))
          ((box? obj)
           (print-box obj port #f))
          ((eof-object? obj)
           (write-string "#<eof-object>" port))
          (else (%write obj port))))))

(define write-shared
  (case-lambda
   ((obj) (write-shared obj (current-output-port)))
   ((obj port)
    (unless (and (output-port? port) (textual-port? port))
      (error "not a textual output port"))
    (cond ((pair? obj) (print-shared obj port #f %print-list))
          ((vector? obj) (print-shared obj port #f %print-vector))
          ((box? obj) (print-shared obj port #f %print-box))
          (else (write obj port))))))

(define write-simple
  (case-lambda
   ((obj) (write-simple obj (current-output-port)))
   ((obj port)
    (unless (and (output-port? port) (textual-port? port))
      (error "not a textual output port"))
    (cond ((pair? obj) (print-simple obj port #f %print-list))
          ((vector? obj) (print-simple obj port #f %print-vector))
          ((box? obj) (print-simple obj port #f %print-box))
          (else (write obj port))))))

(define (quoted-string str quote-char optional-quotes)
  (let ((len (string-length str)))
    (let loop ((i 0) (need-quoting #f) (result '()))
      (if (= i len)
          (if (or (not optional-quotes) need-quoting)
              (string-append (string quote-char)
                             (apply string-append (reverse result))
                             (string quote-char))
              (apply string-append (reverse result)))
          (let* ((ch (string-ref str i))
                 (code (char->integer ch)))
            (case ch
              ((#\alarm) (loop (+ i 1) #t (cons "\\a" result)))
              ((#\backspace) (loop (+ i 1) #t (cons "\\b" result)))
              ((#\tab) (loop (+ i 1) #t (cons "\\t" result)))
              ((#\newline) (loop (+ i 1) #t (cons "\\n" result)))
              ((#\return) (loop (+ i 1) #t (cons "\\r" result)))
              ((#\space) (if (char=? #\| quote-char)
                             (loop (+ i 1) #t (cons " " result))
                             (loop (+ i 1) need-quoting (cons " " result))))
              ((#\") (if (char=? #\" quote-char)
                         (loop (+ i 1) #t (cons "\\\"" result))
                         (loop (+ i 1) need-quoting (cons (string ch) result))))
              ((#\|) (if (char=? #\| quote-char)
                         (loop (+ i 1) #t (cons "\\|" result))
                         (loop (+ i 1) need-quoting (cons (string ch) result))))
              ((#\\) (loop (+ i 1) #t (cons "\\\\" result)))
              (else (if (or (< code 32) (> code 127))
                        (loop (+ i 1) #t (cons (string-append "\\x" (number->string code 16) ";") result))
                        (loop (+ i 1) need-quoting (cons (string ch) result))))))))))

(define (print-char ch port)
  (write-string "#\\" port)
  (case ch
    ((#\alarm) (write-string "alarm" port))
    ((#\backspace) (write-string "backspace" port))
    ((#\delete) (write-string "delete" port))
    ((#\escape) (write-string "escape" port))
    ((#\newline) (write-string "newline" port))
    ((#\null) (write-string "null" port))
    ((#\return) (write-string "return" port))
    ((#\space) (write-string "space" port))
    ((#\tab) (write-string "tab" port))
    (else (let ((code (char->integer ch)))
            (if (and (>= code 32) (<= code 127))
                (write-char ch port)
                (write-string (string-append "x" (number->string code 16)) port))))))

(define (print-bytevector bv port)
  (write-string "#u8(" port)
  (let ((len (bytevector-length bv)))
    (let loop ((i 0))
      (when (< i len)
        (write-string (number->string (bytevector-u8-ref bv i)) port)
        (unless (= i (- len 1))
          (write-char #\space port))
        (loop (+ i 1)))))
  (write-char #\) port))

(define (print-item obj port display? labels used-labels)
  (cond ((pair? obj) (%print-list obj port display? labels used-labels))
        ((vector? obj) (%print-vector obj port display? labels used-labels))
        ((box? obj) (%print-box obj port display? labels used-labels))
        ((or (string? obj) (bytevector? obj))
         (print-with-labels obj port labels used-labels (lambda ()
                                                          (if display?
                                                              (display obj port)
                                                              (write obj port)))))
        (else (if display?
                  (display obj port)
                  (write obj port)))))

(define (print-with-labels obj port labels used-labels print-body)
  (let* ((label (hash-table-ref/default labels obj #f))
         (label-used (if label (hash-table-ref/default used-labels label #f) #f)))
    (if label
        (if label-used
            (begin
              (write-char #\# port)
              (write-string (number->string label) port)
              (write-char #\# port))
            (begin
              (write-char #\# port)
              (write-string (number->string label) port)
              (write-char #\= port)
              (hash-table-set! used-labels label #t)
              (print-body)))
        (print-body))))

(define (%print-list ls port display? labels used-labels)
  (define (print-list-proper)
    (write-char #\( port)
    (print-item (car ls) port display? labels used-labels)
    (let loop ((cur (cdr ls)))
      (if (pair? cur)
          (begin
            (let ((label (hash-table-ref/default labels cur #f)))
              (if label
                  (begin
                    (write-string " . " port)
                    (print-item cur port display? labels used-labels)
                    (write-char #\) port))
                  (begin
                    (write-char #\space port)
                    (print-item (car cur) port display? labels used-labels)
                    (loop (cdr cur))))))
          (begin
            (unless (null? cur)
              (write-string " . " port)
              (print-item cur port display? labels used-labels))
            (write-char #\) port)))))
  (print-with-labels ls port labels used-labels print-list-proper))

(define (print-cyclic obj port display? print)
  (let ((labels (make-eq-hash-table))
        (used-labels (make-eq-hash-table)))
    (walk-for-cycles obj '() labels)
    (print obj port display? labels used-labels)))

(define (print-shared obj port display? print)
  (let ((labels (make-eq-hash-table))
        (used-labels (make-eq-hash-table)))
    (for-each (lambda (item)
                (hash-table-set! labels item (hash-table-size labels)))
              (find-shared-items obj))
    (print obj port display? labels used-labels)))

(define (print-simple obj port display? print)
  (print obj port display? (make-eq-hash-table) (make-eq-hash-table)))

(define (print-list ls port display?)
  (print-cyclic ls port display? %print-list))

(define (%print-vector vec port display? labels used-labels)
  (define (print-vector-proper)
    (write-string "#(" port)
    (let ((len (vector-length vec)))
      (let loop ((i 0))
        (unless (= i len)
          (print-item (vector-ref vec i) port display? labels used-labels)
          (unless (= i (- len 1))
            (write-char #\space port))
          (loop (+ i 1)))))
    (write-char #\) port))
  (print-with-labels vec port labels used-labels print-vector-proper))

(define (print-vector vec port display?)
  (print-cyclic vec port display? %print-vector))

(define (%print-box bx port display? labels used-labels)
  (define (print-box-proper)
    (write-string "#<box value=" port)
    (print-item (unbox bx) port display? labels used-labels)
    (write-char #\> port))
  (print-with-labels bx port labels used-labels print-box-proper))

(define (print-box bx port display?)
  (print-cyclic bx port display? %print-box))

(define (walk-for-cycles obj parents labels)
  (cond ((pair? obj)
         (if (memq obj parents)
             (unless (hash-table-exists? labels obj)
               (hash-table-set! labels obj (hash-table-size labels)))
             (begin
               (walk-for-cycles (car obj) (cons obj parents) labels)
               (walk-for-cycles (cdr obj) (cons obj parents) labels))))
        ((vector? obj)
         (if (memq obj parents)
             (unless (hash-table-exists? labels obj)
               (hash-table-set! labels obj (hash-table-size labels)))
             (let ((len (vector-length obj)))
               (let loop ((i 0))
                 (unless (= i len)
                   (walk-for-cycles (vector-ref obj i) (cons obj parents) labels)
                   (loop (+ i 1)))))))
        ((box? obj)
         (if (memq obj parents)
             (unless (hash-table-exists? labels obj)
               (hash-table-set! labels obj (hash-table-size labels)))
             (walk-for-cycles (unbox obj) (cons obj parents) labels)))))
