(define display
  (case-lambda
   ((obj) (display obj (current-output-port)))
   ((obj port)
    (unless (and (output-port? port) (textual-port? port))
      (error "not a textual output port"))
    (cond ((string? obj)
           (write-string obj port))
          ((symbol? obj)
           (write-string (symbol->string obj) port))
          ((char? obj)
           (write-char obj port))
          ((pair? obj)
           (print-list obj port #t #f))
          ((vector? obj)
           (print-vector obj port #t))
          ((box? obj)
           (print-box obj port))
          (else (write obj port))))))

(define write
  (case-lambda
   ((obj) (write obj (current-output-port)))
   ((obj port)
    (unless (and (output-port? port) (textual-port? port))
      (error "not a textual output port"))
    (cond ((string? obj)
           (write-string (quoted-string obj #\" #f) port))
          ((number? obj)
           (write-string (number->string obj) port))
          ((symbol? obj)
           (write-string (quoted-string (symbol->string obj) #\| #t) port))
          ((boolean? obj)
           (write-string (if obj "#t" "#f") port))
          ((void? obj)
           (write-string "#<void>" port))
          ((char? obj)
           (print-char obj port))
          ((null? obj)
           (write-string "()" port))
          ((pair? obj)
           (print-list obj port #f #f))
          ((vector? obj)
           (print-vector obj port #f))
          ((bytevector? obj)
           (print-bytevector obj port))
          ((box? obj)
           (print-box obj port))
          ((eof-object? obj)
           (write-string "#<eof-object>" port))
          (else (%write obj port))))))

(define (quoted-string str quote-char optional-quotes)
  (let ((len (string-length str)))
    (let loop ((i 0) (need-quoting #f) (result '()))
      (if (= i len)
          (if (or (not optional-quotes) need-quoting)
              (string-append (string quote-char)
                             (apply string-append (reverse result))
                             (string quote-char))
              (apply string-append (reverse result)))
          (let* ((ch (string-ref str i))
                 (code (char->integer ch)))
            (case ch
              ((#\alarm) (loop (+ i 1) #t (cons "\\a" result)))
              ((#\backspace) (loop (+ i 1) #t (cons "\\b" result)))
              ((#\tab) (loop (+ i 1) #t (cons "\\t" result)))
              ((#\newline) (loop (+ i 1) #t (cons "\\n" result)))
              ((#\return) (loop (+ i 1) #t (cons "\\r" result)))
              ((#\space) (if (char=? #\| quote-char)
                             (loop (+ i 1) #t (cons " " result))
                             (loop (+ i 1) need-quoting (cons " " result))))
              ((#\") (if (char=? #\" quote-char)
                         (loop (+ i 1) #t (cons "\\\"" result))
                         (loop (+ i 1) need-quoting (cons (string ch) result))))
              ((#\|) (if (char=? #\| quote-char)
                         (loop (+ i 1) #t (cons "\\|" result))
                         (loop (+ i 1) need-quoting (cons (string ch) result))))
              ((#\\) (loop (+ i 1) #t (cons "\\\\" result)))
              (else (if (or (< code 32) (> code 127))
                        (loop (+ i 1) #t (cons (string-append "\\x" (number->string code 16) ";") result))
                        (loop (+ i 1) need-quoting (cons (string ch) result))))))))))

(define (print-char ch port)
  (write-string "#\\" port)
  (case ch
    ((#\alarm) (write-string "alarm" port))
    ((#\backspace) (write-string "backspace" port))
    ((#\delete) (write-string "delete" port))
    ((#\escape) (write-string "escape" port))
    ((#\newline) (write-string "newline" port))
    ((#\null) (write-string "null" port))
    ((#\return) (write-string "return" port))
    ((#\space) (write-string "space" port))
    ((#\tab) (write-string "tab" port))
    (else (let ((code (char->integer ch)))
            (if (and (>= code 32) (<= code 127))
                (write-char ch port)
                (write-string (string-append "x" (number->string code 16)) port))))))

(define (print-box b port)
  (write-string "#<box value=" port)
  (write (unbox b) port)
  (write-char #\> port))

(define (print-vector vec port display?)
  (write-string "#(" port)
  (let ((len (vector-length vec)))
    (let loop ((i 0))
      (when (< i len)
        (if display?
            (display (vector-ref vec i) port)
            (write (vector-ref vec i) port))
        (unless (= i (- len 1))
          (write-char #\space port))
        (loop (+ i 1)))))
  (write-char #\) port))

(define (print-bytevector bv port)
  (write-string "#u8(" port)
  (let ((len (bytevector-length bv)))
    (let loop ((i 0))
      (when (< i len)
        (write-string (number->string (bytevector-u8-ref bv i)) port)
        (unless (= i (- len 1))
          (write-char #\space port))
        (loop (+ i 1)))))
  (write-char #\) port))

(define (print-list ls port display? middle?)
  (if middle?
      (when (pair? ls)
        (write-char #\space port))
      (write-char #\( port))
  (if (pair? ls)
      (begin
        (if display?
            (display (car ls) port)
            (write (car ls) port))
        (print-list (cdr ls) port display? #t))
      (if (null? ls)
          (write-char #\) port)
          (begin
            (write-string " . " port)
            (if display?
                (display ls port)
                (write ls port))
            (write-char #\) port)))))
