(export *
        +
        -
        ...
        /
        <
        <=
        =
        =>
        >
        >=
        _
        and
        append
        apply
        assoc
        assq
        assv
        begin
        boolean=?
        boolean?
        caar
        cadr
        call-with-current-continuation
        call-with-values
        call/cc
        car
        case
        cdar
        cddr
        cdr
        char->integer
        char-whitespace?
        char<=?
        char<?
        char=?
        char>=?
        char>?
        char?
        close-input-port
        close-output-port
        close-port
        cond
        cons
        current-error-port
        current-input-port
        current-output-port
        define
        define-record-type
        define-syntax
        define-values
        do
        dynamic-wind
        else
        eof-object?
        eq?
        equal?
        eqv?
        error
        error-object?
        error-object-irritants
        error-object-message
        even?
        file-error?
        floor/
        floor-quotient
        floor-remainder
        for-each
        get-output-string
        guard
        if
        include
        input-port?
        integer->char
        integer?
        lambda
        length
        let
        let*
        let-syntax
        let-values
        let*-values
        letrec
        letrec*
        letrec-syntax
        list
        list->string
        list->vector
        list-copy
        list-ref
        list-set!
        list-tail
        list?
        make-list
        make-parameter
        make-string
        make-vector
        map
        max
        member
        memq
        memv
        min
        (rename floor-remainder modulo)
        negative?
        newline
        not
        null?
        number->string
        number?
        open-input-string
        open-output-string
        odd?
        or
        output-port?
        pair?
        parameterize
        peek-char
        port?
        positive?
        procedure?
        quasiquote
        (rename truncate-quotient quotient)
        quote
        raise
        raise-continuable
        read-char
        read-line
        reverse
        (rename truncate-remainder remainder)
        round
        set!
        set-car!
        set-cdr!
        square
        string
        string->list
        string->number
        string->symbol
        string->vector
        string-append
        string-copy
        string-copy!
        string-fill!
        string-for-each
        string-length
        string-map
        string-ref
        string-set!
        string<=?
        string<?
        string=?
        string>=?
        string>?
        string?
        substring
        symbol->string
        symbol=?
        symbol?
        syntax-rules
        truncate/
        truncate-quotient
        truncate-remainder
        unless
        unquote
        unquote-splicing
        values
        vector
        vector->list
        vector->string
        vector-append
        vector-copy
        vector-copy!
        vector-for-each
        vector-fill!
        vector-length
        vector-map
        vector-ref
        vector-set!
        vector?
        when
        with-exception-handler
        write-char
        write-string
        zero?)
